# Generated by Django 2.2.9 on 2020-02-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='img',
        ),
    ]
