# Generated by Django 2.2.9 on 2020-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_remove_pet_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_pet/img'),
        ),
    ]
