# Generated by Django 2.2.9 on 2020-02-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='mypage.Profile'),
        ),
    ]
