# Generated by Django 2.2.9 on 2020-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_auto_20200217_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_pet/img'),
        ),
    ]
